### ISSUE TITLE
Do you have any example code? 

### ISSUE THREAD

**Issue by bsavery** [sampotter/python-embree#1]
A simple geometry example would be good.  I feel like I'm doing something wrong when creating geo:

```
        face_size = len(self.faces[0])
        geo_type = embree.GeometryType.Triangle if face_size == 3 else embree.GeometryType.Quad
        self.device_prim = embree.Geometry(self.device, geo_type)
        buff = self.device_prim.set_new_buffer(embree.BufferType.Vertex, 0, 
                                               embree.Format.Float3, 12, len(self.vertices))
        for i in range(len(self.vertices)):
            buff[i] = self.vertices[i]

        indices_format = embree.Format.Uint3 if face_size == 3 else embree.Format.Uint4
        indices_buff = self.device_prim.set_new_buffer(embree.BufferType.Index, 0,
                                                       indices_format, 4 * face_size,
                                                       len(self.faces))
        for i in range(len(self.faces)):
             indices_buff[i] = self.faces[i]
```

**Comment by bsavery** [comment]
Note that I'm allowing for Triangle and quad geo.  I modified the appropriate types to allow this.

**Comment by bsavery** [comment]
![out](https://user-images.githubusercontent.com/1892220/79283607-4016ea00-7e6d-11ea-89cd-4c3913fdf8a4.png)
Here's the output with a few boxes.  I have to assume I'm doing something wrong with triangle winding order but not sure (parsing the box geo from obj files)

**Comment by bsavery** [comment]
![out](https://user-images.githubusercontent.com/1892220/79283848-e8c54980-7e6d-11ea-8a17-1cdf1ec4cf14.png)
Ah ok.  Displaying the normal dir of the hit points makes it more clear.  Definitely something with the winding direction or indices.

**Comment by bsavery** [comment]
Well I'm an idiot.  OBJ indices start at 1.... not 0.  Sorry for the stream of consciousness

**Comment by sampotter** [comment]
Hi @bsavery, sorry I missed this earlier.

Would you mind sharing this mesh (file or code that you used to create it) and your code? I would like to collect some simple examples to make this wrapper simpler to use for people.

**Comment by bsavery** [comment]
Sure I will.

One thing that finally stopped me working on it was there is no way to get around the python multithreading problem.  That only one thread in python can be active at one time, and embree binding doesn't work with multiprocessing.

**Comment by sampotter** [comment]
Great. Please post the example code/files here.

As for the problem with multithreading, I doubt that would be too hard to fix. If you like, please go ahead and open another issue related to that and we can try to debug it.

**Comment by bsavery** [comment]
[src.zip](https://github.com/sampotter/python-embree/files/4801306/src.zip)
Pretty simple example that runs a path tracer, parses mitsuba xml files.

I should mention that I'm playing around with ways to multithread. or multiprocess.  I'll make that a separate issue.
